using System;
using System.Collections.Generic;

namespace DemoApp.CodeInput;

/// <summary>
/// The demo's words in its two languages: its own under <see cref="KeyPrefix"/>, and in the second language every framework and
/// code field word it registers, so the missing-word report in Development names only a real gap (DemoWordsCoverageTests). The
/// samples and the languages', encodings' and line endings' names stay as written.
/// </summary>
internal static class CodeInputDemoWords
{
    /// <summary>What every key of the demo starts with; every other string is content (<c>KeyPrefixes</c>).</summary>
    public const string KeyPrefix = "code-demo.";

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        ["code-demo.editor.title"] = "Editor",
        ["code-demo.editor.description"] = "A field from NE.Standard.UI.CodeInput. Tab indents, Enter keeps the indentation, Ctrl+F finds and Ctrl+H replaces, Ctrl+U/Ctrl+Shift+U change case, and Ctrl+Space opens completions (a JSON file adds a few .NET names, in every language).",
        ["code-demo.editor.line-numbers"] = "Line numbers",
        ["code-demo.editor.wrap-lines"] = "Wrap lines",
        ["code-demo.editor.read-only"] = "Read-only",
        ["code-demo.editor.search"] = "Search",
        ["code-demo.editor.multi-caret"] = "Multi-caret",
        ["code-demo.editor.status-bar"] = "Status bar",
        ["code-demo.editor.completions"] = "Completions",
        ["code-demo.editor.appearance"] = "Appearance: {appearance}",
        ["code-demo.editor.reset-sample"] = "Reset sample",
        ["code-demo.editor.snippet"] = "Snippet",
        ["code-demo.editor.placeholder"] = "Type some code…",
        ["code-demo.editor.status"] = "On the server: {lines}, {characters}, {encoding}, {ending}.",
        ["code-demo.editor.lines.one"] = "{count} line",
        ["code-demo.editor.lines.other"] = "{count} lines",
        ["code-demo.editor.characters.one"] = "{count} character",
        ["code-demo.editor.characters.other"] = "{count} characters",
        ["code-demo.editor.saved"] = "Saved at {time} — {status}",

        ["code-demo.appearance.ghost"] = "Ghost",
        ["code-demo.appearance.filled"] = "Filled",
        ["code-demo.appearance.outline"] = "Outline",
        ["code-demo.appearance.underline"] = "Underline",

        ["code-demo.markdown.title"] = "Markdown",
        ["code-demo.markdown.description"] = "A code field in Markdown and a MarkdownDisplay bound to the same text; neither knows about the other.",
        ["code-demo.markdown.document"] = "Document",

        ["code-demo.code"] = "Code",
        ["code-demo.copy"] = "Copy"
    };

    // The framework ships English only; an application brings every other language, the framework's and the package's words too.
    // Chinese has one plural form, so a plural key has only its ".other".
    private static readonly Dictionary<string, string> Chinese = new(StringComparer.Ordinal)
    {
        ["code-demo.editor.title"] = "编辑器",
        ["code-demo.editor.description"] = "来自 NE.Standard.UI.CodeInput 的字段。Tab 缩进，Enter 保持缩进，Ctrl+F 查找，Ctrl+H 替换，Ctrl+U/Ctrl+Shift+U 转换大小写，Ctrl+Space 打开补全（一个 JSON 文件在每种语言中添加几个 .NET 名称）。",
        ["code-demo.editor.line-numbers"] = "行号",
        ["code-demo.editor.wrap-lines"] = "自动换行",
        ["code-demo.editor.read-only"] = "只读",
        ["code-demo.editor.search"] = "搜索",
        ["code-demo.editor.multi-caret"] = "多光标",
        ["code-demo.editor.status-bar"] = "状态栏",
        ["code-demo.editor.completions"] = "自动补全",
        ["code-demo.editor.appearance"] = "外观：{appearance}",
        ["code-demo.editor.reset-sample"] = "重置示例",
        ["code-demo.editor.snippet"] = "代码片段",
        ["code-demo.editor.placeholder"] = "输入一些代码…",
        ["code-demo.editor.status"] = "服务器上：{lines}，{characters}，{encoding}，{ending}。",
        ["code-demo.editor.lines.other"] = "{count} 行",
        ["code-demo.editor.characters.other"] = "{count} 个字符",
        ["code-demo.editor.saved"] = "{time} 已保存 — {status}",

        ["code-demo.appearance.ghost"] = "幽灵",
        ["code-demo.appearance.filled"] = "填充",
        ["code-demo.appearance.outline"] = "描边",
        ["code-demo.appearance.underline"] = "下划线",

        ["code-demo.markdown.title"] = "Markdown",
        ["code-demo.markdown.description"] = "一个 Markdown 代码字段和一个绑定到同一文本的 MarkdownDisplay；两者互不知晓。",
        ["code-demo.markdown.document"] = "文档",

        ["code-demo.code"] = "代码",
        ["code-demo.copy"] = "复制",

        ["ui.picker.today"] = "今天",
        ["ui.picker.now"] = "现在",
        ["ui.picker.clear"] = "清除",
        ["ui.picker.done"] = "完成",
        ["ui.picker.previous"] = "上一个",
        ["ui.picker.next"] = "下一个",
        ["ui.picker.hours"] = "小时",
        ["ui.picker.minutes"] = "分钟",
        ["ui.picker.seconds"] = "秒",
        ["ui.picker.meridiem"] = "上午/下午",
        ["ui.picker.start"] = "开始",
        ["ui.picker.end"] = "结束",
        ["ui.picker.open"] = "打开选择器",
        ["ui.notification.close"] = "关闭",
        ["ui.tabs.more"] = "更多标签页",
        ["ui.commandbar.more"] = "更多命令",
        ["ui.tab.close"] = "关闭",
        ["ui.tab.rename"] = "重命名",
        ["ui.tab.pin"] = "固定",
        ["ui.tab.unpin"] = "取消固定",
        ["ui.tab.delete"] = "删除",
        ["ui.select.clear"] = "清除选择",
        ["ui.select.placeholder"] = "请选择…",
        ["ui.select.remove"] = "移除 {label}",
        ["ui.input.clear"] = "清除",
        ["ui.breadcrumbs.label"] = "面包屑导航",
        ["ui.file.uploading"] = "正在上传… {percent}%",
        ["ui.file.count"] = "{count} 个文件",
        ["ui.file.failed"] = "上传失败。",
        ["ui.file.oversized"] = "文件太大。",
        ["ui.file.choose"] = "选择文件",
        ["ui.color.picker"] = "取色器",
        ["ui.color.palette"] = "调色板",
        ["ui.color.hex"] = "十六进制",
        ["ui.color.red"] = "R",
        ["ui.color.green"] = "G",
        ["ui.color.blue"] = "B",
        ["ui.color.factor"] = "系数",
        ["ui.color.opacity"] = "不透明度",
        ["ui.color.choose"] = "选择颜色",
        ["ui.splitter.label"] = "调整大小",
        ["ui.split.more"] = "更多操作",
        ["ui.image.choose"] = "选择图片",
        ["ui.image.change"] = "更换图片",
        ["ui.image.remove"] = "移除图片",
        ["ui.row.edit"] = "编辑",
        ["ui.row.save"] = "保存",
        ["ui.row.cancel"] = "取消",
        ["ui.table.resize"] = "调整列宽",
        ["ui.tree.toggle"] = "展开或折叠",
        ["ui.tree.loading"] = "正在加载…",
        ["ui.items.empty"] = "没有可显示的内容。",
        ["ui.collapse.toggle"] = "展开或折叠",
        ["ui.side.open"] = "打开侧栏",
        ["ui.menu.search"] = "搜索",
        ["ui.theme.switch"] = "切换主题",
        ["ui.language.switch"] = "切换语言，{language}",
        ["ui.notfound.title"] = "404",
        ["ui.notfound.description"] = "你要找的页面不存在。",
        ["ui.notfound.page"] = "页面不存在",
        ["ui.error.title"] = "出了点问题",
        ["ui.error.message"] = "出了点问题，请重试。",
        ["ui.command.refused"] = "你无权执行此操作。",
        ["ui.command.failed"] = "出了点问题，请重试。",
        ["ui.value.format"] = "值的格式不对。",
        ["ui.connection.lost"] = "与服务器的连接已断开。请重新加载页面以继续。",
        ["ui.connection.reload"] = "重新加载",

        ["ui.color.name.iron-fog"] = "铁雾",
        ["ui.color.name.silver-night"] = "银夜",
        ["ui.color.name.bronze-dusk"] = "青铜暮色",
        ["ui.color.name.stellar-red"] = "星红",
        ["ui.color.name.nebula-rose"] = "星云玫瑰",
        ["ui.color.name.lunar-pink"] = "月光粉",
        ["ui.color.name.solar-amber"] = "太阳琥珀",
        ["ui.color.name.nebula-gold"] = "星云金",
        ["ui.color.name.lunar-yellow"] = "月光黄",
        ["ui.color.name.eclipse-olive"] = "日食橄榄",
        ["ui.color.name.nebula-lime"] = "星云青柠",
        ["ui.color.name.lunar-sage"] = "月光鼠尾草",
        ["ui.color.name.aurora-green"] = "极光绿",
        ["ui.color.name.nebula-mint"] = "星云薄荷",
        ["ui.color.name.lunar-fern"] = "月光蕨",
        ["ui.color.name.astral-teal"] = "星青",
        ["ui.color.name.nebula-cyan"] = "星云青",
        ["ui.color.name.lunar-moss"] = "月光苔",
        ["ui.color.name.quantum-blue"] = "量子蓝",
        ["ui.color.name.nebula-aqua"] = "星云水蓝",
        ["ui.color.name.lunar-azure"] = "月光天蓝",
        ["ui.color.name.nova-purple"] = "新星紫",
        ["ui.color.name.nebula-violet"] = "星云紫罗兰",
        ["ui.color.name.lunar-lavender"] = "月光薰衣草",
        ["ui.color.name.comet"] = "彗星",
        ["ui.color.name.flare"] = "耀斑",
        ["ui.color.name.ember"] = "余烬",
        ["ui.color.name.photon"] = "光子",
        ["ui.color.name.vortex"] = "漩涡",
        ["ui.color.name.halo"] = "光环",

        ["ui.code.find"] = "查找",
        ["ui.code.replace"] = "替换",
        ["ui.code.replace-one"] = "替换",
        ["ui.code.replace-all"] = "全部替换",
        ["ui.code.toggle-replace"] = "切换替换",
        ["ui.code.previous"] = "上一个匹配",
        ["ui.code.next"] = "下一个匹配",
        ["ui.code.close"] = "关闭",
        ["ui.code.match-case"] = "区分大小写",
        ["ui.code.whole-word"] = "全字匹配",
        ["ui.code.regex"] = "正则表达式",
        ["ui.code.indentation"] = "缩进",
        ["ui.code.encoding"] = "编码",
        ["ui.code.line-ending"] = "行尾",
        ["ui.code.language"] = "语言",
        ["ui.code.plain-text"] = "纯文本",
        ["ui.code.utf8-bom"] = "UTF-8（带 BOM）",
        ["ui.code.matches"] = "第 {current} 个，共 {total} 个",
        ["ui.code.no-matches"] = "无匹配",
        ["ui.code.invalid-pattern"] = "无效的模式",
        ["ui.code.position"] = "行 {line}，列 {column}",
        ["ui.code.suggestions"] = "建议",
        ["ui.code.spaces-1"] = "1 个空格",
        ["ui.code.spaces-2"] = "2 个空格",
        ["ui.code.spaces-3"] = "3 个空格",
        ["ui.code.spaces-4"] = "4 个空格",
        ["ui.code.spaces-5"] = "5 个空格",
        ["ui.code.spaces-6"] = "6 个空格",
        ["ui.code.spaces-7"] = "7 个空格",
        ["ui.code.spaces-8"] = "8 个空格"
    };

    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Build()
        => new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.Ordinal)
        {
            ["en"] = English,
            ["zh-Hans"] = Chinese
        };
}
