using System.Linq;

namespace DemoApp.CodeInput;

/// <summary>
/// A snippet editor: the language and the field's settings above, the editor filling the page, what the server holds below.
/// </summary>
internal sealed class EditorView : CodeInputDemoView, IUIViewDefinition
{
    public static string ViewKey => "codeinput.editor";

    protected override string Route => EditorRoute;

    public override string Title => "code-demo.editor.title";

    protected override string Description => "code-demo.editor.description";

    protected override DemoPage CreatePage()
        => Page(new ContainerComponent()
            .SetHeight(UILayoutLength.Fill())
            .SetRow(1, UIGridUnit.Auto())
            .AddRow(UIGridUnit.Star())
            .AddRow(UIGridUnit.Auto())
            // Even columns that wrap, so every setting stays in reach on a narrow window and the lines never stagger.
            .AddChild(new WrapPanelComponent()
                .SetSpacing(16)
                .SetLineSpacing(8)
                .SetItemMinWidth(160)
                .SetMargin(UIThickness.All(0, 0, 0, 12))
                .SetHorizontalAlignment(UIAlignment.Stretch)
                .AddChild(new SelectComponent()
                    // The languages the status bar lists, a registered one included: a name as written, plain text's word looked up.
                    .SetOptions([.. UICodeLanguages.All.Select(language => new OptionItem { Id = language.Key, Title = language.Value, IsContent = !UICodeInputStrings.IsWord(language.Value) })])
                    .BindValue(nameof(CodeInputController.Language))
                    .OnChange(nameof(CodeInputController.ChangeLanguage))
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new SwitchComponent()
                    .SetTitle("code-demo.editor.line-numbers")
                    .BindValue(nameof(CodeInputController.LineNumbers))
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new SwitchComponent()
                    .SetTitle("code-demo.editor.wrap-lines")
                    .BindValue(nameof(CodeInputController.WrapLines))
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new SwitchComponent()
                    .SetTitle("code-demo.editor.read-only")
                    .BindValue(nameof(CodeInputController.ReadOnly))
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new SwitchComponent()
                    .SetTitle("code-demo.editor.search")
                    .BindValue(nameof(CodeInputController.Search))
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new SwitchComponent()
                    .SetTitle("code-demo.editor.multi-caret")
                    .BindValue(nameof(CodeInputController.MultiCaret))
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new SwitchComponent()
                    .SetTitle("code-demo.editor.status-bar")
                    .BindValue(nameof(CodeInputController.StatusBar))
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new SwitchComponent()
                    .SetTitle("code-demo.editor.completions")
                    .BindValue(nameof(CodeInputController.Completions))
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new ButtonComponent()
                    .BindTitle(nameof(CodeInputController.AppearanceCaption))
                    .SetType(UIButtonType.Outline)
                    .OnClick(nameof(CodeInputController.CycleAppearance))
                    .SetHorizontalAlignment(UIAlignment.Start)
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .AddChild(new ButtonComponent()
                    .SetTitle("code-demo.editor.reset-sample")
                    .SetType(UIButtonType.Ghost)
                    .OnClick(nameof(CodeInputController.ResetSample))
                    .SetHorizontalAlignment(UIAlignment.Start)
                    .SetVerticalAlignment(UIAlignment.Center)
                )
                .SetPlacement(1, 1, 24, 1)
            )
            .AddChild(new CodeInputComponent()
                .SetTitle("code-demo.editor.snippet")
                // Held in the browser until Ctrl+S sends it (docs/VALUES.md §4): nothing travels while the reader types.
                .SetFormId(CodeInputController.EditorForm)
                .BindValue(nameof(CodeInputController.Code), mode: UIBindingMode.OnSubmit)
                .BindLanguage(nameof(CodeInputController.Language))
                .BindLineNumbers(nameof(CodeInputController.LineNumbers))
                .BindWrapLines(nameof(CodeInputController.WrapLines))
                .BindIsReadOnly(nameof(CodeInputController.ReadOnly))
                .BindSearch(nameof(CodeInputController.Search))
                .BindMultiCaret(nameof(CodeInputController.MultiCaret))
                .BindTabSize(nameof(CodeInputController.TabSize))
                .BindStatusBar(nameof(CodeInputController.StatusBar))
                .BindCompletions(nameof(CodeInputController.Completions))
                // A small sample file under wwwroot, offered whatever the language; see "Completions" in the package's README for the JSON shape.
                .SetCompletionsSource("/completions/csharp.json")
                .BindEncoding(nameof(CodeInputController.Encoding))
                .BindLineEnding(nameof(CodeInputController.LineEnding))
                .BindAppearance(nameof(CodeInputController.Appearance))
                .OnSave(nameof(CodeInputController.Save))
                .SetPlaceholder("code-demo.editor.placeholder")
                .SetHeight(UILayoutLength.Fill())
                .SetHorizontalAlignment(UIAlignment.Stretch)
                .SetPlacement(1, 2, 24, 1)
            )
            .AddChild(new TextComponent()
                .BindTitle(nameof(CodeInputController.Status))
                .SetTitleType(UITextAppearance.Caption)
                .SetTitleColor(UIThemeColor.FromStyle(UIColorStyle.Muted))
                .SetMargin(UIThickness.All(0, 8, 0, 0))
                .SetPlacement(1, 3, 24, 1)
            )
        );
}
